openapi: 3.0.0
info:
  title: Personal Portfolio Website
  description: Personal Portfolio Website API
  version: 0.1.9

servers:
  - url: https://portfolio-api-production-99be.up.railway.app
    description: production server
  - url: http://localhost:5000/api
    description: local server
paths:
  /projects:
    get:
      tags:
        - projects
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /tech:
    get:
      tags:
        - Tech
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /me:
    get:
      tags:
        - Me
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
