openapi: 3.0.0
info:
  title: Personal Portfolio Website
  description: Personal Portfolio Website API
  version: 0.1.9

servers:
  - url: https://portfolio-api-production-99be.up.railway.app/api
    description: production server
paths:
  /projects:
    get:
      tags:
        - projects
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /techs:
    get:
      tags:
        - Tech
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /skills:
    get:
      tags:
        - Business
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /mes:
    get:
      tags:
        - Mes
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /sendemail:
    post:
      tags:
        - Email
      requestBody:
        description: Send Email
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                subject:
                  type: string
                message:
                  type: string
            example:
              name: Node is awesome
              email: Don't use nodemon on server
              subject: Node is awesome
              message: Don't use nodemon on server
      responses:
        "200":
          description: Email sent
